language: node_js
services:
- docker
cache:
  directories:
  - "~/.nvm"
  - node_modules
env:
  global:
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT="nebo15"
  - MAIN_BRANCHES="master develop"
  - secure: gnrWqSRqRLiXLwsXlxLZ/TzCjqMeue81CkE+TDa8fIpHDusCIwWCLAritNRmGOX6UR76U2m1TiX+M+zfW76cNggN+xmdzeW+HgMcHNjBVNipVqOiv6YXr8qpH5P9oPwhSUgKy/F29DfZ2vfDgCLbNt8TfdM/7cVPfgt1j9N/SypR1kZTkkVQgFdupNNk1CqCDMrnKm3Gj+r9bkScOHPRZfpbg3Wun1G9iZqYMydIOHauZd/D/wiccYsbQRfX4mUoW9x/4g/5YhFOmjtbRZZ4SvjDUPrdcPj69kw7R14m5/NuG5sxrhuAzm2kMkyVuAiZooiTXLTuA5qorcaABnpRVJ8Yr/3zj860WVIOIYHmhvXrDqrEZtwLoAaUh0Uoc4vwMsrSyqVOuYB8US6kswcuOEWwce7X2Kt3dUI/g6WmgTFcPLetoyfxQ9jzMvh/Ab5KeLYKwQ9LW7dOPHi7cd5uMOD1ubOlb1gnYEsgGiswBkbobV4jL5hfpqB5TSCcBZjKZMQOkFfgzHe6oKA5LLdvKflYTUNCm1lP7MUinVxA0QkW2CSPLZnhOo9bEYWBELIAg7SGjvtykPdApAYTNGG1yidFB/1j61b4pYXGq8JUZBvmhJoVVhYufsUz6P1/nA9nEmFpaUB4qDeClxzB8M+1ob/Wb64Fr4jLBovjEh6S7kY=
node_js:
- 7.5.0
before_install:
- npm run docker:up
- chmod -R +x bin
script:
- npm run test
- npm run lint
- "./bin/version-increment.sh"
- "./bin/build.sh"
- "./bin/start.sh"
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`; if [ "${RUNNING_CONTAINERS//[[:space:]]/}"
  == "1" ]; then echo "[E] Container is not started\!"; docker logs annon.status.web
  --details --since 5h; exit 1; fi;
- npm run nightwatch -- -e travis
- sleep 5
after_success:
- "./bin/ci/push.sh"
